### ISSUE TITLE
Problem with curl on Ubuntu 12.04

### ISSUE THREAD

**Issue by afniedermayer** [JuliaLang/BinDeps.jl#122]
When trying to install the package Blosc, I get the following error message:

```julia

julia> Pkg.build("Blosc")
INFO: Building Blosc
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0curl: (77) error setting certificate verify locations:
  CAfile: /etc/pki/tls/certs/ca-bundle.crt
  CApath: none
================================[ ERROR: Blosc ]================================

failed process: Process(`curl -o c-blosc-1.5.0.tar.gz -L https://github.com/Blosc/c-blosc/archive/v1.5.0.tar.gz`, ProcessExited(77)) [77]
while loading /home/andras/.julia/v0.3/Blosc/deps/build.jl, in expression starting on line 16

================================================================================

================================[ BUILD ERRORS ]================================

WARNING: Blosc had build errors.

 - packages with build errors remain installed in /home/andras/.julia/v0.3
 - build the package(s) and all dependencies with `Pkg.build("Blosc")`
 - build a single package by running its `deps/build.jl` script

================================================================================

julia> versioninfo()
Julia Version 0.3.5
Commit 21d5433* (2014-10-21 20:18 UTC)
Platform Info:
  System: Linux (x86_64-linux-gnu)
  CPU: Intel(R) Core(TM) i7 CPU         920  @ 2.67GHz
  WORD_SIZE: 64
  BLAS: libopenblas (NO_LAPACK NO_LAPACKE DYNAMIC_ARCH NO_AFFINITY Nehalem)
  LAPACK: liblapack.so.3
  LIBM: libopenlibm
  LLVM: libLLVM-3.3
```
---

After changing the order of `(:curl, :wget, :fetch)` to `(:wget, :curl, :fetch)` in `BinDeps.download_cmd`, it works, so it's likely to be a problem with curl.

**Comment by tkelman** [comment]
Are you behind a proxy or anything unusual? Are you up-to-date on security fixes from `apt-get`?

**Comment by staticfloat** [comment]
```
curl: (77) error setting certificate verify locations:
  CAfile: /etc/pki/tls/certs/ca-bundle.crt
  CApath: none
```

It sounds like you're missing the `ca-certificates` package.  Could you `sudo apt-get install ca-certificates` and see if that helps?

**Comment by tkelman** [comment]
Shouldn't curl declare a dependency on that? Did curl come from apt-get or somewhere else?

**Comment by staticfloat** [comment]
It looks like `curl` [doesn't depend on it](https://gist.github.com/staticfloat/9fbeb3d0812c3c74ff34).

**Comment by afniedermayer** [comment]
I just updated to the newest stable Julia (`0.3.5~precise4`) and cannot reproduce the error any more.

Here's what I did:
I reverted the order in BinDeps to the original `(:curl, :wget, :fetch)` (from the `(:wget, :curl, :fetch)` I had locally for which everything worked). I uninstalled `Blosc`, deleted the package files in the cache and reinstalled `Blosc`. Everything works without any problems.

I guess something in the newest update must have fixed this. (I don't know what, since neither BinDeps nor Blosc seem to have changed...)

(Considering the questions: I have `curl` from `apt-get` and I have `ca-certificate` installed, also from `apt-get`. I'm not behind a proxy.)

Thanks @tkelman and @staticfloat !

**Comment by afniedermayer** [comment]
Ok, this is strange. I couldn't reproduce the error on my home computer. (I had already installed the `Blosc` package using a patch of `BinDeps`.)

Now I tried on my office computer (also Ubuntu 12.04, with a proxy, behind a firewall). The error shows up again. Here's the output:

```
julia> Pkg.add("Blosc")
INFO: Installing Blosc v0.1.1
INFO: Building Blosc
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0curl: (77) error setting certificate verify locations:
  CAfile: /etc/pki/tls/certs/ca-bundle.crt
  CApath: none
================================[ ERROR: Blosc ]================================

failed process: Process(`curl -o c-blosc-1.5.0.tar.gz -L https://github.com/Blosc/c-blosc/archive/v1.5.0.tar.gz`, ProcessExited(77)) [77]
while loading /home/niedermayer/.julia/v0.3/Blosc/deps/build.jl, in expression starting on line 16

================================================================================

================================[ BUILD ERRORS ]================================

WARNING: Blosc had build errors.

 - packages with build errors remain installed in /home/niedermayer/.julia/v0.3
 - build the package(s) and all dependencies with `Pkg.build("Blosc")`
 - build a single package by running its `deps/build.jl` script

================================================================================
INFO: Package database updated
```
Package `ca-certificates` is installed through `apt-get`. `curl` was not installed through `apt-get`. Installing it through `apt-get` didn't remove the error.

I'm not sure why I couldn't reproduce the error on my home computer. Maybe I didn't delete all the files from the installed `Blosc` package that I already had.

**Comment by afniedermayer** [comment]
And the versioninfo for my office computer:
```
julia> versioninfo()
Julia Version 0.3.5
Commit a05f87b* (2015-01-08 22:33 UTC)
Platform Info:
  System: Linux (x86_64-linux-gnu)
  CPU: Intel(R) Xeon(R) CPU           X5650  @ 2.67GHz
  WORD_SIZE: 64
  BLAS: libopenblas (NO_LAPACK NO_LAPACKE DYNAMIC_ARCH NO_AFFINITY)
  LAPACK: liblapack.so.3
  LIBM: libopenlibm
  LLVM: libLLVM-3.3
```

**Comment by staticfloat** [comment]
Some other resources on the 'net suggested doing an `apt-get update && apt-get upgrade`.  Could it be that those commands haven't been run in a while?

**Comment by afniedermayer** [comment]
I just ran `sudo apt-get update && sudo apt-get upgrade` and the same error still shows up.

**Comment by staticfloat** [comment]
Sorry, but I don't know why your `curl` is misbehaving then.  If you find out, please do let us know, but as it stands, we've had very few problems with `curl` on other people's systems, so we're probably not going to switch the default order.

**Comment by afniedermayer** [comment]
No problem. Thanks for looking into this. I'll let you know if I find out.

**Comment by tkelman** [comment]
Just to be sure, are you able to run `curl -o c-blosc-1.5.0.tar.gz -L https://github.com/Blosc/c-blosc/archive/v1.5.0.tar.gz` successfully outside of Julia? If not, then I do think this is something particular about your network/proxy/firewall setup.

**Comment by afniedermayer** [comment]
`curl` gave the same error outside of Julia. After some google-ing, I finally found a solution: I just put the line `cacert=/etc/ssl/certs/ca-certificates.crt` into the `~/.curlrc` file. (The certificates were stored at a different location than what curl thought.) 

`curl` in Julia works now, too.

Here's the resource I found most helpful, in case someone runs into similar problems:
http://stackoverflow.com/questions/3160909/how-do-i-deal-with-certificates-using-curl-while-trying-to-access-an-https-url

Maybe the problem was that I had upgraded from Ubuntu 10.04 to 12.04.

Thanks for your help!

**Comment by tkelman** [comment]
Ah, interesting, thanks for posting the link in case anyone else hits this. I don't think there's much for us to do here, and you found a non-Julia fix for the problem, so I'll close the issue. Leave another comment or open a new issue if you have any other trouble though.

**Comment by HackerMD** [comment]
I also ran into the problem on our cluster. By changing line 48 
checkcmd in (:wget, :curl, :fetch) -> checkcmd in (:curl, :wget :fetch)
I could solve the problem and Blosc could be build successfully.

**Comment by abieler** [comment]
Had the same problem on Linux Mint 17 (Ubuntu 14.04), putting
```cacert=/etc/ssl/certs/ca-certificates.crt``` into ```~/.curlrc``` fixed the problem!
Thanks!

**Comment by milkers** [comment]
Thank you so much! I am also using Mint 17 and had the same problem. afniedermayer's post solved my issue.

**Comment by sb43** [comment]
This helped to resolve peakrescue installation issue, thanks

**Comment by JulianPasc** [comment]
This solved the problem for me: http://stackoverflow.com/a/30154802
Thanks!

**Comment by leokhachatorians** [comment]
Nice, I was also having the same issue on 15.04
