### ISSUE TITLE
0.4 tuple changes prevent BinDeps from loading

### ISSUE THREAD

**Issue by tkelman** [JuliaLang/BinDeps.jl#141]
caused by https://github.com/JuliaLang/julia/pull/10380
```
  | | |_| | | | (_| |  |  Version 0.4.0-dev+4319 (2015-04-17 03:26 UTC)
 _/ |\__'_|_|_|\__'_|  |  Commit ef06211* (0 days old master)
|__/                   |  x86_64-linux-gnu

julia> using BinDeps
ERROR: LoadError: LoadError: TypeError: apply_type: in alias, expected Type{T}, got Tuple{DataType,DataType}
 in include at ./boot.jl:250
 in include_from_node1 at ./loading.jl:129
 in include at ./boot.jl:250
 in include_from_node1 at ./loading.jl:129
 in reload_path at ./loading.jl:153
 in _require at ./loading.jl:68
 in require at ./loading.jl:51
while loading /home/tkelman/.julia/v0.4/BinDeps/src/dependencies.jl, in expression starting on line 16
while loading /home/tkelman/.julia/v0.4/BinDeps/src/BinDeps.jl, in expression starting on line 489
```

**Comment by veryluckyxyz** [comment]
I just upgraded to 0.4. Because of this error, I am not able to build packages that have binary dependencies (Homebrew, IJulia being some)

**Comment by mlubin** [comment]
@veryluckyxyz, I wouldn't recommend using 0.4 unless you're a developer and have a specific reason to. It will certainly be quite unstable during the next few days if not longer. If you'd like to lend a hand, feel free to submit PRs to the affected packages.

**Comment by veryluckyxyz** [comment]
Thanks @mlubin for your recommendation. I am aware that it will be unstable. I was merely trying to emphasize its importance. I am sorry that my comment sounded to you like I was whining that a dev version is not stable.
