### ISSUE TITLE
Conda provider ?

### ISSUE THREAD

**Issue by Luthaf** [JuliaLang/BinDeps.jl#151]
[conda](http://conda.pydata.org/) is a nice package manager from the python world. It can handle any kind of binary package.

It also have a very appreciated feature scientific binary libraries: anyone can upload its own package to [binstar](http://binstar.org/), and have people download it from there. So If I want to make my binary library available to the world, it would be easier to built it by myself and upload it than trying to get it in all the linux distributions over there, plus WinRPM or nuget, plus Homebrew.

My question is then would it be possible to have a conda provider for BinDeps ? Should it be a package like WinRPM.jl or Homebrew.jl ?

**Comment by tkelman** [comment]
I have had this exact same idea and think it is absolutely an idea that should be looked into. Yes, it should be implemented as a Conda.jl separate provider, as WinRPM.jl and Homebrew.jl do. You'd probably have to implement reading and utilizing conda's metadata format to resolve dependencies, download and extract.

Unless binstar has changed since the last time I tried it, they don't provide an automated build service for windows or mac binaries, do they? Conda's pre-compiled packages would be most valuable on Linux where currently we're either hoping system distro package managers have new enough versions to work, or building from source on every user's system. Maybe homebrew could also be useful, but the existing conda binaries can occasionally be pretty strongly constrained by compatibility concerns with matching the "system native" Python interpreter. Julia on Windows for example uses an entirely different compiler than Python on Windows. Not sure what the situation is like on OSX, but are there any major issues with our current Homebrew.jl mechanism there?

**Comment by Luthaf** [comment]
>  they don't provide an automated build service for windows or mac binaries, do they? 

They do, but only for paid users. Appveyor can be used to automate the build of windows binaries and you would need a mac to build OS X versions.

> conda binaries can occasionally be pretty strongly constrained by compatibility concerns with matching the "system native" Python interpreter.

Conda install it's own python interpreter, so it do not needs to use the "official" one. Anyway, python is completely optional at either build or run time in conda.

> You'd probably have to implement reading and utilizing conda's metadata format to resolve dependencies, download and extract.

Why not just shelling stuff to the `conda` binary, and letting it decide what to do ? `run('conda install foo')` should do the trick, the hardest part being to install conda itself.

**Comment by tkelman** [comment]
> Appveyor can be used to automate the build of windows binaries and you would need a mac to build OS X versions.

I don't think manually building everything, or trying to manually script appveyor, is scalable for large libraries with non-trivial dependencies. WinRPM and Homebrew are quite a bit better at managing dependencies (both build time and run time, separately) than anything else even close to as simple to use.

Is it possible to download from conda's package repository without introducing any dependency on Python? This is still a major bootstrapping/installation problem with IJulia.

**Comment by Luthaf** [comment]
> Is it possible to download from conda's package repository without introducing any dependency on Python? This is still a major bootstrapping/installation problem with IJulia.

I am not sure what you mean here. A fresh miniconda install produce the following output:
```
installing: python-2.7.9-1 ...
installing: conda-env-2.1.4-py27_0 ...
installing: openssl-1.0.1k-1 ...
installing: pycosat-0.6.1-py27_0 ...
installing: pyyaml-3.11-py27_0 ...
installing: readline-6.2-2 ...
installing: requests-2.6.0-py27_0 ...
installing: sqlite-3.8.4.1-1 ...
installing: tk-8.5.18-0 ...
installing: yaml-0.1.4-1 ...
installing: zlib-1.2.8-0 ...
installing: conda-3.10.1-py27_0 ...
Python 2.7.9 :: Continuum Analytics, Inc.
creating default environment...
installation finished.
```
So python is installed (conda is written in python), and a few others dependencies. But the packages installed by conda do not have a Python dependency (as in library dependency), unless explicitly stated.

> I don't think manually building everything, or trying to manually script appveyor, is scalable for large libraries with non-trivial dependencies.

The conda recipe should handle the dependencies management. If you need the libraries A, B and C, just write in the `meta.yml` file
```yaml
requirements:
  build:
    - A
    - B
    - C
  run:
    - A
    - C
```

Then `conda build recipe-dir` will ensure to install all the dependencies, and run the build script for the package (`./configure --prefix=$PREFIX && make install` is the simplest one).

**Comment by tkelman** [comment]
Conda won't bootstrap a posix environment on windows like cygwin or msys2 (or cross-compile from linux) that would be needed to run `./configure && make` on Windows. MSVC-built binaries are generally to be avoided with Julia packages at this time, if a MinGW-built alternative version is available.

I think the main benefit here would be as a distribution-independent, non-root-requiring (right?) binary package provider for Linux. It's a step sideways at best for other platforms.

**Comment by Luthaf** [comment]
> Conda won't bootstrap a posix environment on windows like cygwin or msys2 (or cross-compile from linux) that would be needed to run ./configure && make on Windows.

The `./configure && make` was only an example. A conda recipe consist of three main files: `meta.yml` describe the package, `build.sh` is run to build on UNIX, and `bld.bat` is run to build on Windows. And that is not for the bootstrap part, but only for the package building. The bootstrap part can be handled with [miniconda](http://conda.pydata.org/miniconda.html)

> MSVC-built binaries are generally to be avoided with Julia packages at this time, if a MinGW-built alternative version is available.

Even for library used through a C interface ? Isn't the C stdlib the same for MSVC and MinGW ?

>  non-root-requiring (right?) 

Yes. Conda also try to provide relocatable package by replacing any library path by a rpath.

**Comment by tkelman** [comment]
> Even for library used through a C interface ? Isn't the C stdlib the same for MSVC and MinGW ?

Sometimes it'll work. It depends on the library and what it's doing. The MSVC standard library is different depending on which version of visual studio you build with, either msvcr110.dll or msvcr120.dll etc. MinGW links against msvcrt.dll, which is a default component included in the OS (was the name visual studio used prior to some very old version, it's kept around under that same name for backwards-compatibility reasons). Some things can work, as long as you don't use stdcall calling convention on 32 bit (may get fixed eventually? https://github.com/JuliaLang/julia/pull/7486), and as long as you don't do things like try to malloc memory in one C runtime version and free it in a different one, across a shared library boundary. It might work in some cases but I don't expect it to be reliable. We hit some of these issues with HDF5 and a few other packages, in cases where upstream does provide official MSVC-built Windows dlls, but they hit issues when ccall'ed from Julia.

**Comment by Luthaf** [comment]
First steps are here : https://github.com/Luthaf/Conda.jl !

I have only tested it on OS X. It should work the same way on Linux, but I am not sure about the Windows installer for Miniconda.
