### ISSUE TITLE
Any blockers for tagging a new release?

### ISSUE THREAD

**Issue by IainNZ** [JuliaLang/BinDeps.jl#156]
Deprecation warnings are making me depressed

**Comment by yuyichao** [comment]
That's what I'm feeling too :).

**Comment by tkelman** [comment]
Sounds like https://github.com/JuliaLang/BinDeps.jl/issues/155 is no different on master vs the current tag, so go ahead. I would've done it myself for #153 but I don't have access to my ssh keys right now.

**Comment by IainNZ** [comment]
Alright, I'll pull the trigger. May PkgEval have mercy on our souls.

**Comment by IainNZ** [comment]
https://github.com/JuliaLang/METADATA.jl/pull/2842
