### ISSUE TITLE
What's the correct URI for a local file?

### ISSUE THREAD

**Issue by dpo** [JuliaLang/BinDeps.jl#182]
I'm writing an extension for which users should obtain the source archive on their own; it's not available for direct download. Users should place the tar.gz archive somewhere (I'm thinking in the `BinDeps.depsdir` of the library dependency). When I write `provides(Sources, URI(...), ...)`, how am I supposed to specify the `URI`?

**Comment by mlubin** [comment]
I don't think Bindeps has any special mechanism for this. Look at https://github.com/JuliaOpt/Mosek.jl/blob/master/deps/build.jl and https://github.com/JuliaOpt/Gurobi.jl/blob/master/deps/build.jl

**Comment by dpo** [comment]
Thanks. I found a way to do what I needed:
https://github.com/dpo/HSL.jl/blob/master/deps/build.jl#L70

It would help to have more examples in the `BinDeps` doc.
