### ISSUE TITLE
julia0.5 dlopen api change

### ISSUE THREAD

**Issue by vtjnash** [JuliaLang/BinDeps.jl#184]
PR https://github.com/JuliaLang/julia/pull/13796 caused issues for BinDeps where it does a direct ccall to a function that no longer exists in base at https://github.com/JuliaLang/BinDeps.jl/blob/e35913637c1c30149bcc7bdba5bd5ebede711efa/src/dependencies.jl#L510-L519l

**Comment by tkelman** [comment]
What's the fix? Please don't leave this broken.

**Comment by vtjnash** [comment]
probably `handle = ccall(:jl_dlopen,Ptr{Void},(Ptr{UInt8},Cuint),opath,flags)` and remove the malloc/free

**Comment by Carreau** [comment]
The following works like a charm, not that I know what I am doing. 
```
diff --git a/src/dependencies.jl b/src/dependencies.jl
index 61cde23..196b5ba 100644
--- a/src/dependencies.jl
+++ b/src/dependencies.jl
@@ -507,16 +507,7 @@ end

 function check_path!(ret,dep,opath)
     flags = Libdl.RTLD_LAZY
-    handle = Libc.malloc(2*sizeof(Ptr{Void}))
-    err = ccall(:jl_uv_dlopen,Cint,(Ptr{UInt8},Ptr{Void},Cuint),opath,handle,flags)
-    if err == 0
-        check_system_handle!(ret,dep,handle)
-        Libdl.dlclose(handle)
-        # in Julia 0.4 handle is freed by dlclose.
-        if VERSION < v"0.4-"
-            c_free(handle)
-        end
-    end
+    handle = ccall(:jl_dlopen,Ptr{Void},(Cstring,Cuint),opath,flags)
 end
```

**Comment by yuyichao** [comment]
You probably want to keep the `check_system_handle!` and add version checks too.

Actually why is this not just using `Libdl.dlopen`?

**Comment by Ph0non** [comment]
With the fix from @yuyichao it's not working for me. Still the same error. If I change the line
```handle = ccall(:jl_dlopen, Ptr{Void}, (Ptr{UInt8}, Cuint), opath, flags)``` to 
```handle = ccall(:jl_dlopen,Ptr{Void},(Cstring,Cuint),opath,flags)``` like suggested from @Carreau it works.

**Comment by tkelman** [comment]
Strange. Can you open that as a PR?
