### ISSUE TITLE
Any plans to add openSUSE zypper/Yast to the list of package managers?

### ISSUE THREAD

**Issue by colbec** [JuliaLang/BinDeps.jl#188]
Using openSUSE Leap 42.1:
Just wondering if there is any argument why zypper might not be on the list of things to add.
Right now, if Julia finds it has to recompile stale cache files for PyPlot for example, there is a strange call which opens up a window for Yast package manager wanting root access, presumably to pull in or modify existing binaries. Dismissing this window allows the process to continue, and PyPlot appears to work correctly at least on simple plots.

**Comment by tkelman** [comment]
Nobody has added it yet, but I'd be happy to review and help anyone who'd like to try writing a pull request to add support for opensuse packages here. It's quite a nice distro, really great build service and we use its cross compiled packages on windows, but I think it's a little less popular than debbuntu, fedora, and arch. Natural to add support for it though.

I think PyPlot should be using Conda.jl for its binary deps these days, it might be something else like Nettle.jl or ZMQ.jl causing the yast popup if you're using IJulia. Try Pkg.build for a few packages to see if you can identify which one it is.

**Comment by colbec** [comment]
Agreed, code only needs to be added as and when there is a demand, and for less popular distros the additions come a bit later. I have posted a request at the openSUSE forums to see if there is any previous work, but no response so far. The science repo has a working version of v4 so there is a chance that someone has already beaten this bush already.

I tested 'build' on the suggested packages but none of them triggered the yast issue. I will keep trying the growing list of installed packages. IJulia no longer seems to be causing the yast popup, although it was a few days ago.

I'm not really familiar with git pulls or Julia programming but I am willing to give it a go. I'm assuming that I just have to make mods to file dependencies.jl using say pacman as a template. We'll see how it goes.

**Comment by colbec** [comment]
I have opened a pull request at https://github.com/colbec/BinDeps.jl
Not sure if it has landed in the right place, so I am offering the link here.

**Comment by colbec** [comment]
OK, puzzled by the way my detection of zypper is progressing.
I have inserted some test code which shows that my zypper is found and the flags are set.
The puzzle is that the Yast window pops up before the code apparently starts looking for it.
So I'm stuck on two things:
1. something in the code is triggering Yast before it is asked for
2. when I try to display the name of the package that the process is looking for ($(?.package)) the compiler tells me that ? is not defined.

**Comment by nalimilan** [comment]
What is `$(?.package)` supposed to do? That's a very weird syntax, which would work only if the variable `?` holds an object with a `package` field.

**Comment by tkelman** [comment]
Which line at https://github.com/colbec/BinDeps.jl/pull/2/files are you referring to? And no, that wound up in the wrong place. You should open a pull request against JuliaLang/BinDeps.jl:master from colbec/BinDeps.jl:colbec-patch-2

**Comment by colbec** [comment]
Thanks for comments by nalimilan and tkelman. As you can tell I am a beginner with this process.
Undaunted, here is some further info:
1. no response from the openSUSE forums, so I guess I am the only one looking at this issue
2. Steven G Johnson tells me that PyPlot does not directly use BinDeps, so that avenue is no help
3. referring to my colbec-patch-2, the critical line is 213; at this point has_zypper(z.package) and can_use(...) are set, but 213 complains that z is not defined. I guess it must be because success() failed. I will look again. I used a ? wildcard in my question since there seems to be a pattern of p for pacman, a for aptget. Could be wrong.
4. I will review the github instructions on pull requests again. Kinda lost in the hierarchy here but the clouds will clear.

**Comment by tkelman** [comment]
We're happy to help get you up to speed, we all had to start somewhere. Just let us know if you have any questions.

**Comment by tkelman** [comment]
I seem to remember @ronisbr being one of the contributors to the OpenSUSE packaging of Julia itself, and may be willing/able to help with testing here.

**Comment by colbec** [comment]
Good idea about the openSUSE packagers. I found several email addresses in the change log for the Julia v4 package and have pinged ronisbr.
With regard to the proper location for the pull request, I guess I have to create a new request and just be very careful with parameters.
Probably best for me to hold back until I hear from one of the packagers.

**Comment by ronisbr** [comment]
Hi @colbec!
I had this exactly same problem with julia v0.4 and PyPlot.
I'm not sure how can we fix it, but I will be glad to help you since it is very annoying.
Is there any think I can do from the openSUSE side?

**Comment by nalimilan** [comment]
@colbec If you want us to see the changes you made, you need to make a pull request. See this page:
http://docs.julialang.org/en/latest/manual/packages/#code-changes
and the links at the bottom of this page: https://github.com/JuliaLang/julia/blob/master/CONTRIBUTING.md

Please just ask if you encounter problems in that process.

**Comment by colbec** [comment]
@ronisbr - I am running openSUSE Leap 42.1 here, glad to see you are on board for this investigation
@nalimilan, thanks for the references, very helpful; it seems that in my brute force attempts to edit and test recompile files I have disrupted my Julia installation. It is giving me nasty errors such as deserialization checks failed and precompile is true but require failed to ... So I am going to scrap my current install and start from scratch. Back when I can.

**Comment by colbec** [comment]
OK followed the link instructions, all ok up to Pkg.submit("BinDeps") but my install does not have Pkg.submit()? Now searching, but if you have suggestions...

**Comment by nalimilan** [comment]
If you're on Julia git master, these features have moved to the `PkgDev` package, so `PkgDev.submit()` (a message should have told you this, https://github.com/JuliaLang/julia/pull/14228).

**Comment by colbec** [comment]
That helped, but Bad Credentials is stopping me now.
Reset my github password no problem.
BTW the linked instructions may be slightly out of date, the PkgDev told me that I needed to set "github.user" and not "user.name".
Searching now on "Bad Credentials"... and fingers crossed I can complete the work performed so far. The Pkg.test step launched a huge number of compiles and downloads. Quite the performance!

**Comment by colbec** [comment]
Got it. git config was looking for github username, I was stuck on full name. Duh.
PkgDev ran, I was presented with a link, followed it and created pull request.

**Comment by nalimilan** [comment]
@colbec If you found places where the instructions are incorrect or unclear, please file an issue, as you're in the best position to tell us what needs improvements.

Regarding the PR (https://github.com/JuliaLang/BinDeps.jl/pull/189), your code looks good to me (at least from a superficial look). I don't see how `z` could be undefined in `package_available()`.

As @tkelman noted, the fact that Yast starts might be a completely different issue, which wouldn't be fixed by your PR for BinDeps. We'll need to tackle it separately.

**Comment by colbec** [comment]
@nalimilan I appreciated your guidance in getting the PR to the right place. Thankyou.
Point taken on the instructions, I will put something together.
Having now followed the recommended procedure which produced a specific result, it is quite possible that my previous hack attempt at modifying dependencies.jl and testing it was entirely inappropriate and produced a misleading result.
The last few times I have issued "using PyPlot" there have been no calls to Yast on my system, but this might just mean that the cache does not need to be refreshed. I won't say any more until everything is cool for a week without problems. The Pkg.test step did a lot of stuff on my installation, most of which I could not follow.

**Comment by nalimilan** [comment]
I think you should clean your PR by removing the comments about"new" and "temporary", and if you confirm it works it could be merged.

Then let's take care of the Yast thing. It likely comes from Conda.jl. I know nothing about Conda, but it sounds possible to me that it would try to install packages using Yast. You can force building PyPlot again by calling `Pkg.build("PyPlot")` and/or by removing `~/.julia/PyPlot.jl` and `~/.julia/.cache/PyPlot.jl`. If Yast doesn't show up again, it might be because you installed the needed packages. Anyway, you can start by filing an issue against PyPlot.jl or against Conda.jl

**Comment by colbec** [comment]
I'd be interested in the view of @ronisbr on the changes in this package before asking for a merge. In future I will leave the comments out - it looks as though diff does a good job of highlighting changes anyway. Force of habit.

Pkg.build did not work well in combination with deletion of cache files. "PyPlot is not an installed package" from build and "unknown package" from Pkg.add. Pkg.update() got me back on track and precompiled PyPlot, and there were no calls to Yast. Now that I have the required packages, I guess I am useless as a tester.

I spoke to PyPlot already, they said "Not us" and closed the issue immediately. This leaves Conda as a candidate. I will see what they have to say.

**Comment by nalimilan** [comment]
Please give the references to the issues you cite (this one is https://github.com/stevengj/PyPlot.jl/issues/183). After looking a bit more, it looks like PyPlot.jl doesn't use Conda automatically by default. So I'm not sure where it comes from. Could you look at the history of recently installed distribution packages? Then you should be able to find out which packages you need to remove to trigger the problem again. If you can do that, you'll be able to install the Julia packages PyPlot.jl depends on separately, and to identify the culprit.

**Comment by ronisbr** [comment]
@colbec, do you mean PR #189?

Well, I'm not that expert in julia language yet, but I have some comments on the PR:

1) `zypper info` will return information about any package available on the enabled repositories. Thus, it will return information even if the package is not installed. Is that what you want?

2) You are looking for the string `Version:`. As it is, it seems dangerous because calling `zypper info` will output a localized text. Thus, here for example, I do not have `Version:` but `Versão:` instead. Maybe you need to be sure that LANG=C is set before calling `zypper info`

**Comment by colbec** [comment]
@nalimilan Unfortunately it looks like the system did not use Yast to install any packages; at least nothing is reported in the history. The only installs showing are those completed manually this morning from the repos. I remember them. From what I recall in the test process there were some direct downloads of source (output similar to wget) followed by local build of packages. I don't know how this fits into the narrative, just reporting what I saw.

@ronisbr Excellent feedback, thanks. Unfortunately I'm getting rapidly out of my depth, not knowing really what the process is expecting. I will do some reading, but clearly the suggestion needs fine revision.

**Comment by nalimilan** [comment]
@colbec OK, so in that case you can move out all of your `~/.julia` directory, and then try to install one by one the PyPlot.jl dependencies. Once you're done, remove `~/.julia` and put the old version of the directory in its place.

**Comment by colbec** [comment]
I have updated my original RP189 to remove comments as requested. New RP190 created - I was not sure if this was the right step to do, whether the original updated RP189 would survive the process with the commits, so to be safe I created a second RP. Tell me if that is wrong, by all means.

I also thought about the comment by @ronisbr about different locales and made a change to shorten up the string so that both Version and Versao would be seen, I think. Maybe a kludge, but I have no idea how Julia handles multiple locales. Just following the pattern in other sections of code.

So a more general question about the declarative nature of Julia code. We can look at code and speculate about what the controller will do with it, but really the acid test is whether it passes the Pkg.test() process that determines whether the attempted code is suitable or not. Is this a fair statement? From previous experience with declarative programming it is likely that the BinDeps code is read multiple times and each time some incremental step is made towards a solution. How Julia puts these together is up to Pkg.test to fathom.

**Comment by nalimilan** [comment]
> I have updated my original RP189 to remove comments as requested. New RP190 created - I was not sure if this was the right step to do, whether the original updated RP189 would survive the process with the commits, so to be safe I created a second RP. Tell me if that is wrong, by all means.

That's one way, another is to use git to force-push the branch in order to update the existing PR. (Tip: when you refer to a PR, paste the full URL and git will shorten it.)

> I also thought about the comment by @ronisbr about different locales and made a change to shorten up the string so that both Version and Versao would be seen, I think. Maybe a kludge, but I have no idea how Julia handles multiple locales. Just following the pattern in other sections of code.

Good, but I wouldn't shorten the string: only for some latin languages it will start with `Ver`, and if in the future zypper prints another line starting with `Ver`, it will fail. I think you'd better include the ending `:` (if it's printed that way, I don't know; else, maybe a space) to protect against this.

To always get the English output, set LC_ALL when calling the command that way:
```julia
env = copy(ENV)
env["LC_ALL"] = "C"
for l in eachline(setenv(`zypper info $(z.package)`, env))
...
```

(Indeed it looks like other providers need this fix too.)

> So a more general question about the declarative nature of Julia code. We can look at code and speculate about what the controller will do with it, but really the acid test is whether it passes the Pkg.test() process that determines whether the attempted code is suitable or not. Is this a fair statement? From previous experience with declarative programming it is likely that the BinDeps code is read multiple times and each time some incremental step is made towards a solution. How Julia puts these together is up to Pkg.test to fathom.

Julia isn't a declarative language, so I'm not sure what you mean. But in any language running the tests is the best way to check the code is correct. Though in the present case I don't think it's enough, since there are no tests for distribution-specific providers (they can't be run all on the same system).

**Comment by colbec** [comment]
Hmmm, I guess you are right about Julia not being declarative, it stuck in my mind that I read that somewhere but I can't find it again. You are right too about other providers needing environment revision; I don't feel qualified to run these additions - all I can see is some kind of huge switch or if-else if construction looming.

I think I am about done on this issue for now, it the community chooses to merge it and apply further revisions that's ok, otherwise this discussion might just save someone work in the future.

**Comment by nalimilan** [comment]
Could you just apply the LC_ALL change and write "Version" in full? Other providers can be fixed later, but at least let's do this correctly from the beginning for zypper (and it will create an example for future fixes).

**Comment by ronisbr** [comment]
Yes, setting LC_ALL=C is the best approach.

**Comment by colbec** [comment]
My latest update attempt #193  has gone down in flames due to environment issues. Good try but no champagne.

**Comment by nalimilan** [comment]
What do you mean?

**Comment by colbec** [comment]
@nalimilan I corrected the things requested and submitted a new commit for my patch 2 in #193. When the system ran checks, it reports "all checks failed." Specifically test "travis cl" with "no environment variables set." I If these details are not visible to you then maybe I have pressed the wrong button again.

**Comment by nalimilan** [comment]
@colbec The error appears to be a missing `end`: `ERROR: syntax: incomplete: "function" at /home/travis/.julia/v0.3/BinDeps/src/dependencies.jl:335 requires end`

**Comment by colbec** [comment]
@nalimilan Thanks for the feedback. I repaired the end and resubmitted. The test is now running, and tests .1 to .3 are good, waiting on .4 to .6. The execution time for the test seems to be long, running now for almost 30 minutes. Previous tests have been quite quick. Is the testing server subject to time of day loads? The long execution would otherwise make me suspicious that I do not have it right yet.

**Comment by nalimilan** [comment]
Not sure, but the tests passed now. Do you know how to squash the commits, or should I do it for you?

**Comment by yuyichao** [comment]
@colbec The execution time of the tests shouldn't depend on other factors but the wait time in the queue would. You can click the travis link and see how long the test actually take and it seems normal.

**Comment by colbec** [comment]
@yuyichao Thanks for the reassurance. Each of the tests .1 to .6 took about 3-4 minutes which I could only explain by having things waiting for other things to finish. 

@nalimilan This is the first I heard of squashing commits; I can imagine what it means but have no idea how to do it from the web interface. WRT uname, did we eliminate the test for uname deliberately? I may have dropped a test completely without good reason - it appears in yum but not in pacman. It also explains where the found_* vars came from. Do we really need uname? I will have to defer to other expert opinion on that, perhaps @ronisbr ?

**Comment by nalimilan** [comment]
> WRT uname, did we eliminate the test for uname deliberately? I may have dropped a test completely without good reason - it appears in yum but not in pacman. It also explains where the found_* vars came from. Do we really need uname? I will have to defer to other expert opinion on that, perhaps @ronisbr ?

I don't know about Zypper, but it looks like to me that RPM-based systems allow installing either the x86_64 or i686 version of a package. I would copy the code for Yum as-is, and keep it if it works for you. It can help in some special cases.

**Comment by colbec** [comment]
I have a question wrt a section of the code for Cairo/deps/build.jl beginning line 53 where a section begins with a comment "System Package Managers" and goes on to call provides() which I think comes from BinDeps (hence the question here). There are items for AptGet and Yum, but again nothing for Zypper. If a section for Zypper, with the appropriate equivalent fields for the rpm based manager, were added, would BinDeps know how to handle it? It looks like a few edits are needed in the deps aliases there as well to match Zypper equivalents.

**Comment by tkelman** [comment]
@colbec yes that's the idea. Once we add your modifications here so BinDeps knows how to invoke zypper, then packages like Cairo can add another few lines for zypper package names and library aliases.

**Comment by colbec** [comment]
@tkelman @nalimilan Added back #193 the yum package check and removed the found_version var which I don't think is used. Commits seem to have passed the test.

**Comment by nalimilan** [comment]
@colbec Thanks, looks good to me. Can you squash the commits, or should I do it for you?

@tkelman That `found_uname` logic sounds broken to me even in the Yum provider. The `continue` instruction is run conditionally on the value of `found_uname` corresponding to the *previous* iteration. I would have written this `endswith(l, uname) || continue` instead. `found_version` and `found_uname` could be removed.

**Comment by colbec** [comment]
@nalimilan It would be much appreciated if you would perform the squash on this occasion. It would be nice to get something committed, even if not exactly what the community would prefer, and then make a few extra tweaks in their own right.

**Comment by nalimilan** [comment]
@colbec OK, I will do that before merging, if nobody objects.

@kmsquire You added the code for the Yum backend in cf54fbaf9a8b48407c27fc9d94b36fbdfb1ab779, any remarks about the `found_uname` issue I noted in my previous comment?

**Comment by nalimilan** [comment]
Thanks, @colbec! I've pushed your changes directly as I don't have the permissions to update your PR.
