### ISSUE TITLE
library dependency that requires another library in DYLD_LIBRARY_PATH

### ISSUE THREAD

**Issue by chkwon** [JuliaLang/BinDeps.jl#212]
I'm writing a package that depends on a binary library file, called `libpath47`. This requires `libgfortran` to be in `DYLD_LIBRARY_PATH`. (I'm currently working with `osx`.)

```julia
using BinDeps
@BinDeps.setup
libgfortran = library_dependency("libgfortran", aliases=["libgfortran.dylib", "libgfortran.3.dylib"])
```

This dependency is passed. To provide `libpath47`, I did:

```julia
libpath47 = library_dependency("libpath47", aliases=["libpath47.dylib"])
provides(Binaries, URI("https://github.com/ampl/pathlib/archive/master.zip"), libpath47, unpacked_dir = "pathlib-master/lib/osx/", os = :Darwin)
@BinDeps.install Dict(:libpath47 => :libpath47)
```
which fails to pass the dependency check.
```
LoadError: Provider BinDeps.Binaries failed to satisfy dependency libpath47
```

If I manually add `libgfortran` to be in `DYLD_LIBRARY_PATH` by editing `.bash_profile`, it works good. Should I (and users of my package) do this work manually?

**Comment by nalimilan** [comment]
Maybe you could pass a custom validation function via `validate`, and call `dlopen()` on the `libgfortran` path before opening  `libpath47`?

**Comment by chkwon** [comment]
@nalimilan I don't know how to use `validate`, but I tried this:

```
Libdl.dlopen("/opt/homebrew-cask/Caskroom/julia/0.4.5/Julia-0.4.5.app/Contents/Resources/julia/lib/julia/libgfortran.3.dylib", Libdl.RTLD_GLOBAL)

libpath47 = library_dependency("libpath47")
provides(Binaries, URI("https://github.com/ampl/pathlib/archive/master.zip"), libpath47, unpacked_dir = "pathlib-master/lib/osx/", os = :Darwin)
@BinDeps.install Dict(:libpath47 => :libpath47)
```
and it didn't work.

Not sure if I did `dlopen()` correctly.

**Comment by chkwon** [comment]
It was an issue of `rpath`.
