### ISSUE TITLE
Bindeps not finding library file in custom binary path

### ISSUE THREAD

**Issue by mbrookhart** [JuliaLang/BinDeps.jl#246]
Escalating this [Issue](https://github.com/JuliaIO/ImageMagick.jl/issues/44)

I've got ImageMagick compiled in a custom location on a work server running SUSE.  I'm trying to install the ImageMagick.jl package, which requires a certain shared library file to exist on the computer. To do this, I set an environment variable that points my library location.  This works fine, but when the ImageMagick build.jl script reaches this line:

`provides(Binaries, mpath, libwand)`

it doesn't find the dependency, even though the required .so file is in mpath. 

Is there anyway to debug why it isn't finding the library?

Thanks

**Comment by tkelman** [comment]
BinDeps.debug, or try dlopen'ing the library and see if that fails for any reason

**Comment by mbrookhart** [comment]
dlopen succeeds. 

running build.jl fails with the error:
ERROR: LoadError: None of the selected providers can install dependency libwand.`
at the line
`@BinDeps.install Dict([(:libwand, :libwand)])`

BinDeps.debug fails because ImageMagick doesn't come with a deps.jl file, so BinDeps.debug can't read it.

**Comment by tkelman** [comment]
Oh, it's because binaries aren't in the default provider list on Linux https://github.com/JuliaLang/BinDeps.jl/blob/115b2288460c15a1e9d1af23e25f473d672124a4/src/dependencies.jl#L614

**Comment by mbrookhart** [comment]
That would do it.  Adding Binaries to that line then gives the error:

`LoadError: MethodError: no method matching generate_steps(::BinDeps.LibraryDependency, ::BinDeps.CustomPathBinaries, ::Dict{Symbol,Any})`

Looks like remote binaries are supported, but CustomPathBinaries aren't, despite the doc?

`Binaries:

If given a URI object as its data argument, indicates that the binaries may be downloaded from the provided URI. It is assumed that the binaries unpack the libraries into usr/lib. If given a String as its data argument, provides a custom search path for the binaries. A typical use might be to allow the user to provide a custom path by using an environmental variable.`

**Comment by tkelman** [comment]
That looks familiar. I think @malmaud saw something like that when he was working on MbedTLS recently and put a workaround there instead of adding the code here.

**Comment by mbrookhart** [comment]
Looks like it's broken all the way back to #99.

**Comment by mbrookhart** [comment]
Stale, closing, haven't revisited the issue.
