### ISSUE TITLE
Determine what BLAS/LAPACK Julia was built against

### ISSUE THREAD

**Issue by dpo** [JuliaLang/BinDeps.jl#247]
Is there a programmatic way of determining what BLAS/LAPACK libraries Julia was built against and obtaining the location of those libraries?

The purpose is to compile extension packages against the same BLAS/LAPACK as Julia.

Thanks.

**Comment by nalimilan** [comment]
I think `Libdl.dlpath(Base.libblas_name)` should do the trick. But please use the mailing lists for questions and keep GitHub for actual bug reports.

**Comment by dpo** [comment]
Apologies. Because my question around from reflexions on BinDeps, I thought the answer might have to do with BinDeps. Your command works. Thanks.
