### ISSUE TITLE
Broken on 0.6?

### ISSUE THREAD

**Issue by barche** [JuliaLang/BinDeps.jl#252]
I get the following error on 0.6-nightly:
https://travis-ci.org/JuliaInterop/CxxWrap.jl/jobs/182105166#L118

Is this a know issue? The tests on 0.5 do pass and they used to pass on 0.6 until about a week ago, so I guess it's related to a change in Julia.

**Comment by tkelman** [comment]
Not a BinDeps error, it's a regression in the array type. There is an open base PR that may help.
