### ISSUE TITLE
calling the library in validation

### ISSUE THREAD

**Issue by lobingera** [JuliaLang/BinDeps.jl#269]
the readme says:

> while the handle is a handle that may be passed to ccall or dlsym to check library symbols or the return value of function.

I've been pointed out here https://github.com/JuliaGraphics/Cairo.jl/pull/175#discussion_r104319014 to check library version in build. But 
```
julia> Pkg.build("Cairo")
INFO: Building Cairo
================================[ ERROR: Cairo ]================================

LoadError: TypeError: validate_cairo_version: in ccall: first argument not a pointer or valid constant expression, expected Ptr{T}, got Tuple{Symbol,Ptr{Void}}
while loading /home/lobi/.julia/v0.5/Cairo/deps/build.jl, in expression starting on line 160

================================================================================
...
```
the code to validate is this
```
# check for cairo version 
function validate_cairo_version(name,handle)
    v = ccall((:cairo_version,handle),Int32,())        
    return v > 11200
end
...
   cairo = library_dependency("cairo", aliases = ["libcairo-2", "libcairo","libcairo.so.2", "libcairo2"], depends = [gobject,fontconfig,libpng], group = group, validate = validate_cairo_version)
...
```

full PR here: https://github.com/JuliaGraphics/Cairo.jl/pull/175

**Comment by nalimilan** [comment]
Not sure whether the form you tried is supposed to work, but in StringEncodings I use:
```julia
function validate_iconv(n, h)
    f = Libdl.dlsym_e(h, "iconv_open")
    f == C_NULL && return false

    cd = ccall(f, Ptr{Void}, (Cstring, Cstring), "ASCII", "UTF-8")
...
```

**Comment by lobingera** [comment]
@nalimilan I had a similar idea on the table because i remembered the problems with getting non-constant term in the first argument of ccall, but the documentation mentioned 
> while the handle is a handle that may be passed to ccall 

so i'd thought, give it a try - maybe they have solved this.  -> Just a documentation issue?

**Comment by nalimilan** [comment]
I suspect that's a documentation issue since `?ccall` doesn't say that a library handler can be passed to it.

**Comment by lobingera** [comment]
@Keno You put this into the documentation, any comments?

**Comment by tkelman** [comment]
a handle should work in ccall, either the documentation is missing in ccall or that stopped working at some point

**Comment by lobingera** [comment]
@tkelman I tend to agree (that i rather should work like explained in the doc and with ccall), but even with a shallow search in githup "validate  extension:jl path:/deps" i only find examples using the handle with Libc.dlsym or dlsym_e and no direct ccall. Do you remember a fully functional ccall validate?

**Comment by yuyichao** [comment]
AFAICT this never worked. Not since 0.3.

**Comment by lobingera** [comment]
but then the best solution is: Update doc and provide a Libc.dlysim and ccall(Libc.dlsym_e example?

**Comment by lobingera** [comment]
is in documentation with #270
