### ISSUE TITLE
Linux + Binaries provider

### ISSUE THREAD

**Issue by SimonDanisch** [JuliaLang/BinDeps.jl#272]
Any reasons for this subtle difference on different platforms?
https://github.com/JuliaLang/BinDeps.jl/blob/master/src/dependencies.jl#L614
Including Binaries in linux seems to work kind of fine...
How would I activate this in my build script? Or does this need a PR to BinDeps directly?

**Comment by tkelman** [comment]
https://github.com/JuliaLang/BinDeps.jl/pull/163

**Comment by SimonDanisch** [comment]
Thanks, was only searching issues...
