### ISSUE TITLE
new tag

### ISSUE THREAD

**Issue by musm** [JuliaLang/BinDeps.jl#279]
for upcomming changes

**Comment by musm** [comment]
Bump

**Comment by musm** [comment]
I should add the ref https://github.com/JuliaLang/BinDeps.jl/issues/279

**Comment by tkelman** [comment]
Probably also a good time to drop 0.4 support, rather than worrying about whether the 0.6 bugfixes cause issues there.

**Comment by musm** [comment]
https://github.com/JuliaLang/BinDeps.jl/pull/284

**Comment by musm** [comment]
If you want to hold off on #284 for some time , do you mind tagging Bindeps in its current state? Thanks

**Comment by musm** [comment]
Is it possible to tag please? It's pretty easy to make a tag and shouldn't take much time. Even if someone notices a bug, a patch release is just as easy and quick so I don't see why not.
