### ISSUE TITLE
`Binaries` provider can't handle archives that unzip to the same directory

### ISSUE THREAD

**Issue by ssfrr** [JuliaLang/BinDeps.jl#290]
I'm downloading a binary `.zip` file for Windows that has the DLL file in the root of the archive, but it doesn't seem that there's an `unpacked_dir` option for that. Currently I have:

```julia
provides(Binaries, URI("http://www.rarewares.org/files/mp3/libmp3lame-3.99.5x64.zip"), lame,
         SHA="97959980490caa1669b1c4af386c3e23fe4ceed0835c04e328c9a5966e4d2521",
         unpacked_dir="")
```

I've also tried `unpacked_dir="."`, but with `""` it interprets it as `libmp3lame-3.99.5x64` (from [this line](https://github.com/JuliaLang/BinDeps.jl/blob/70d4cab063de4f6adbeb63dbf466b4719bc5b767/src/BinDeps.jl#L357)), and with `"."` it complains that "Provider BinDeps.Binaries failed to satisfy dependency libmp3lame" (maybe it's looking for the literal `.` as the filename?

Is there an incantation that can handle this zip file?

**Comment by tkelman** [comment]
I remember having tried to deal with that somewhere (NLopt maybe?) and failed to find something that worked concisely.

**Comment by ssfrr** [comment]
Ah yes, looks like [here](https://github.com/JuliaOpt/NLopt.jl/blob/488068e9b7302546f136b7029ca6fc94de7c279d/deps/build.jl#L36-L48) you just run the download/unpack steps manually with a `BuildProcess`. Thanks for the pointer.

**Comment by tkelman** [comment]
That code has been there in NLopt for a really long time, https://github.com/JuliaOpt/NLopt.jl/commit/020f3a8af423709e6dc78f32c5d9bd3178898af6

it's pretty messy unfortunately - be sure to do the
```
if is_windows()
    push!(BinDeps.defaults, BuildProcess)
end

@BinDeps.install Dict(:libnlopt => :libnlopt)

if is_windows()
    pop!(BinDeps.defaults)
end
```
to avoid leaving side-effects behind for the next package that might get built in the same process (on 0.6 each package builds in its own process now so this is less likely to be an issue, but on 0.5 it could make a difference)

**Comment by tkelman** [comment]
https://github.com/JuliaOpt/NLopt.jl/pull/49 was my attempt to do it nicer using basically what you tried, maybe it could be made to work but don't remember how deeply I tried to debug this
