### ISSUE TITLE
Require certain gcc?

### ISSUE THREAD

**Issue by jgorham** [JuliaLang/BinDeps.jl#299]
Hello,

I'm using BinDeps to compile a cpp library I use in our package, and unfortunately it doesn't compile with older versions off gcc [it does compile when using gcc v5.3.0]. Is there a way I can require this or at least fail with an error message if this version isn't installed?

**Comment by tkelman** [comment]
I don't think this was your problem (see https://github.com/jgorham/SteinDiscrepancy.jl/pull/2), but there are a few things you could do. If you don't have control over the code you're building, you could add an extra little check program that gets run first and outputs a useful error message. If you're using autotools or cmake they usually have some built-in features that can automate this kind of thing, but if your project is just a few files then you could do it in the source with some preprocessor conditionals.

**Comment by jgorham** [comment]
Oh, interesting! It appears that the linux box I was trying it on would have had two errors then? Either way, I've merged in your changes, as everything is still fine on OSX.
